name: Deploy to EC2 Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy the DNS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/dns-ai
            git pull

            # Only Building
            docker compose -f docker-compose-prod.yaml build

            # Restart container
            docker compose -f docker-compose-prod.yaml up -d